version: '3.8'

services:
  nginx-lb:
    image: nginx:alpine
    container_name: nginx-load-balancer
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./load-balancer.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs:/var/log/nginx
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
